-- ============================================================
-- SINIESTRO WEB V2 - SUPABASE / POSTGRESQL
-- ESQUEMA LIMPIO Y COMPATIBLE CON EL PROYECTO
-- ============================================================
-- IMPORTANTE:
-- Este script elimina las tablas anteriores para evitar errores
-- como: column "nosiniestro" does not exist.
-- Ejecutar TODO el archivo en Supabase > SQL Editor.
-- ============================================================

DROP VIEW IF EXISTS public.vista_siniestros CASCADE;
DROP TABLE IF EXISTS public.comentarios CASCADE;
DROP TABLE IF EXISTS public.siniestros CASCADE;
DROP TABLE IF EXISTS public.aseguradoras CASCADE;
DROP FUNCTION IF EXISTS public.actualizar_fecha_modificacion() CASCADE;

-- ============================================================
-- ASEGURADORAS
-- ============================================================

CREATE TABLE public.aseguradoras (
    id_aseguradora BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- SINIESTROS
-- ============================================================

CREATE TABLE public.siniestros (
    id_siniestro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nosiniestro VARCHAR(50) NOT NULL UNIQUE,
    tipo_cliente VARCHAR(20) NOT NULL DEFAULT 'particular',
    orden INTEGER NOT NULL DEFAULT 0,
    modelo VARCHAR(100) NOT NULL,
    color VARCHAR(50) NOT NULL,
    placas VARCHAR(20) NOT NULL,
    fecha_actualizacion DATE NOT NULL DEFAULT CURRENT_DATE,
    id_aseguradora BIGINT NULL,
    refacciones NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    mano_obra NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    telefono VARCHAR(20) NULL,
    estatus_taller VARCHAR(30) NOT NULL DEFAULT 'valuacion',
    fecha_estatus_taller DATE NOT NULL DEFAULT CURRENT_DATE,
    terminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_tipo_cliente
        CHECK (tipo_cliente IN ('particular', 'aseguradora')),

    CONSTRAINT chk_estatus_taller
        CHECK (estatus_taller IN (
            'valuacion',
            'autorizacion',
            'reserva',
            'esperando_piezas',
            'citar',
            'citado',
            'colission'
        )),

    CONSTRAINT fk_siniestro_aseguradora
        FOREIGN KEY (id_aseguradora)
        REFERENCES public.aseguradoras(id_aseguradora)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- ============================================================
-- COMENTARIOS
-- ============================================================

CREATE TABLE public.comentarios (
    id_comentario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_siniestro BIGINT NOT NULL,
    comentario TEXT NOT NULL,
    fecha_comentario TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_comentario_siniestro
        FOREIGN KEY (id_siniestro)
        REFERENCES public.siniestros(id_siniestro)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- ÍNDICES
-- ============================================================

CREATE INDEX idx_siniestros_nosiniestro
    ON public.siniestros(nosiniestro);
CREATE INDEX idx_siniestros_orden
    ON public.siniestros(orden);
CREATE INDEX idx_siniestros_placas
    ON public.siniestros(placas);
CREATE INDEX idx_siniestros_modelo
    ON public.siniestros(modelo);
CREATE INDEX idx_siniestros_fecha_actualizacion
    ON public.siniestros(fecha_actualizacion);
CREATE INDEX idx_siniestros_aseguradora
    ON public.siniestros(id_aseguradora);
CREATE INDEX idx_siniestros_tipo_cliente
    ON public.siniestros(tipo_cliente);
CREATE INDEX idx_siniestros_fecha_estatus
    ON public.siniestros(fecha_estatus_taller);
CREATE INDEX idx_siniestros_terminado
    ON public.siniestros(terminado);
CREATE INDEX idx_siniestros_estatus
    ON public.siniestros(estatus_taller);
CREATE INDEX idx_comentarios_siniestro
    ON public.comentarios(id_siniestro);

-- ============================================================
-- ASEGURADORAS INICIALES
-- ============================================================

INSERT INTO public.aseguradoras (nombre) VALUES
('AXA'),
('GNP'),
('Qualitas'),
('HDI'),
('Chubb'),
('Mapfre'),
('Zurich'),
('ABA'),
('Banorte'),
('Afirme'),
('Otra');

-- ============================================================
-- TRIGGER: FECHA DE MODIFICACIÓN
-- ============================================================

CREATE OR REPLACE FUNCTION public.actualizar_fecha_modificacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fecha_modificacion = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_siniestros_fecha_modificacion
BEFORE UPDATE ON public.siniestros
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

-- ============================================================
-- VISTA GENERAL
-- ============================================================

CREATE OR REPLACE VIEW public.vista_siniestros AS
SELECT
    s.id_siniestro,
    s.nosiniestro AS "No. Siniestro",
    s.tipo_cliente AS "Tipo Cliente",
    s.orden AS "Orden",
    s.modelo AS "Modelo",
    s.color AS "Color",
    s.placas AS "Placas",
    a.nombre AS "Aseguradora",
    s.fecha_actualizacion AS "Última Actualización",
    s.refacciones AS "Refacciones",
    s.mano_obra AS "Mano de Obra",
    (s.refacciones + s.mano_obra) AS "Total",
    s.telefono AS "Teléfono",
    s.estatus_taller AS "Estatus Taller",
    s.fecha_estatus_taller AS "Fecha Etapa",
    CASE
        WHEN s.tipo_cliente = 'particular' THEN 'Particular'
        ELSE COALESCE(a.nombre, 'Sin aseguradora')
    END AS "Cliente / Aseguradora",
    s.terminado AS "Terminado",
    s.fecha_creacion AS "Fecha Creación",
    s.fecha_modificacion AS "Fecha Modificación"
FROM public.siniestros s
LEFT JOIN public.aseguradoras a
    ON s.id_aseguradora = a.id_aseguradora;

-- ============================================================
-- RLS
-- El backend usa SUPABASE_SECRET_KEY, que tiene privilegios
-- para operar aunque RLS esté habilitado.
-- ============================================================

ALTER TABLE public.aseguradoras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.siniestros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comentarios ENABLE ROW LEVEL SECURITY;

-- Acceso para el cliente publicable si posteriormente se usa
-- directamente desde frontend. En producción conviene sustituir
-- estas políticas por reglas basadas en autenticación.
CREATE POLICY "public_read_aseguradoras"
ON public.aseguradoras FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "public_read_siniestros"
ON public.siniestros FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "public_read_comentarios"
ON public.comentarios FOR SELECT
TO anon, authenticated
USING (true);

-- ============================================================
-- PRUEBAS
-- ============================================================

SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'siniestros'
ORDER BY ordinal_position;

SELECT * FROM public.aseguradoras ORDER BY id_aseguradora;
SELECT * FROM public.siniestros ORDER BY orden, id_siniestro;
